services:
  redis:
    image: "redis"
    container_name: queue
    expose:
      - 6379
    ports:
      - 6379:6379
  app:
    build: 
      context: .
      args:
        - NODE_ENV_ARG=development
    command: npm run back-end-dev
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 6363:8080
    environment:
      - REDIS_CONNECTION_STRING=redis://queue:6379
      - NODE_ENV=development
      - CORS_ORIGIN=["localhost:8080"] # optional if you don't have CORS involved