services:
  redis:
    image: "redis:alpine"
    container_name: queue
    expose:
      - 6379
  app:
    build: .
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 6363:8080
    environment:
      - FLY_REDIS_CACHE_URL=redis://queue
      - NODE_ENV=production
      - CORS_ORIGIN=["localhost:8080"] # optional if you don't have CORS involved