apiVersion: v2
name: in-person-queue
description: Location-based real-time queues, with an optional bundled Valkey
type: application
version: 0.1.0
appVersion: '2.0.0'
home: https://github.com/barakplasma/in-person-queue
sources:
  - https://github.com/barakplasma/in-person-queue
