apiVersion: v1
kind: Service
metadata:
  name: {{ include "iq.fullname" . }}
  labels: {{- include "iq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "iq.selector" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
