name: Node.js CD from master

on:
  push:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 5
    env:
      PORT: 3000
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    container: mcr.microsoft.com/playwright:latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - name: Deploy to fly.io
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"