name: PR builder

on:
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 5
    env:
      PORT: 3000
      REDIS_HOST: redis:6379
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    container: mcr.microsoft.com/playwright:latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
